### PR TITLE
Add logs window

### PR DESCRIPTION
**Pull request by jchyzy**

### CODE REVIEW

**Comment by pswedrak** [comment]
I cannot run application from this branch. I get FileNotFoundError (/widgets_templates/logs.ui)

**Comment by jchyzy** [comment]
Ok, previously I added this missing file. I also moved this functionality to another file (it was in deploy jupyter while the _show logs button_ is outside tabs).

**Comment by PiekarzKarolina** [comment]
Logs don't close when the IdactGUI is closed, please fix that.

**Comment by PiekarzKarolina** [comment]
There are some new errors here, there shouldn't be any.
`QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
QDialog::exec: Recursive call detected`

**Comment by PiekarzKarolina** [comment]
No comments to he code from me, only this two issues.

**Pull request closed without merging**
